### ISSUE TITLE
Server crash on loading Surveyor Map Framework

### ISSUE THREAD

**Issue by KeinoxX** [sisby-folk/surveyor#59]
[crash-2024-11-16_07.57.37-server.txt](https://github.com/user-attachments/files/17783949/crash-2024-11-16_07.57.37-server.txt)

**Comment by sisby-folk** [comment]
So uh, i'm pretty sure we catch this error. EOFExceptions extend IOExceptions, so this should be dutifully logged and the code should move on.

![image](https://github.com/user-attachments/assets/c6d65edd-702f-434c-b523-5ec05c9c9d08)

Anyway you killed your server while it was saving surveyor save data and there's a partial file. Delete the save data in world/data/surveyor.

The catch is supposed to tell you which file is problematic. The catch is not occurring, and i have no idea why. Ball's out of my court, just wipe all the dat files starting with c.

**Comment by KeinoxX** [comment]
Thx for the help, but I have already decided to remove the mod. And what is strange is that after removing your mod, the server's RAM consumption and its startup time decreased by a significant amount.

For example: with mod server nedeed minimum 11gb RAM, after deleting him just 5gb RAM.
And server starting with mod be 2 minutes, after deleting just 30 seconds.

For a mod just on the map (not even on bosses or dimensions), your mod requires too much for me.
I wish this problem be solved and good luck :3

**Comment by sisby-folk** [comment]
I'd kill to get a download of your surveyor map data that decompresses into 6gb, I genuinely don't have the time to generate that much map data. surveyor doesn't have a streaming load system whatsoever (I'm not that skilled yet), it loads 100% of map data into ram, so I'm not surprised.

**Comment by sisby-folk** [comment]
the game probably hanged at both load and save, which is why you killed the server during save - could've taken minutes at a time. it's hard to profile without these extremely large save files to test, so if you can zip up your data/surveyor folder and upload it somewhere that would help

**Comment by KeinoxX** [comment]
Thanks again, but I won't check it because users are actively playing on my server. 
I hope you can solve my original problem as well as the problem with consumption. 
I dont know if it is worth closing the problem since it has not been solved as I understand it, so you will close it at your discretion.
Good luck
(I translated this message with google translator and some words can be take another mean(but this line i translated myself))
